### ISSUE TITLE
PHP version compatibility.

### ISSUE THREAD

**Issue by Maikuolan** [shieldfy/shieldfy-php-client#55]
In regards to PHP version compatibility, the Composer/Packagist information for the Shieldfy PHP client currently indicates `"php" : "~5.6|~7.0"`. Out of curiousity; Are there currently any known compatibility problems between the Shieldfy PHP client and newer PHP versions (`PHP >= 7.1`), or has compatibility with newer PHP versions been tested yet? I could do some local testing, if needed. Worth asking first though, I think. :-)

**Comment by Maikuolan** [comment]
Scratch that.. A misunderstand on my part regarding tilde constraints in Composer. I double-checked the Composer documentation after posting this issue, clearing that up.. My bad. Resolved.

**Comment by komicho** [comment]
No problem, bro
